### ISSUE TITLE
Disable XP gain while dead

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#16]

**Comment by tinygiant98** [comment]
I don't have a fork (so no PR) and I'm not familiar enough to know if you have a special marker for dead PCs, but this should do the trick (not the cleanest, but it works).  Should still give credit to party members that are alive.

script:  party_credit
lines:  251-255

```
  if (GetObjectType(OBJECT_SELF) == OBJECT_TYPE_CREATURE && !GetIsDead(oPC))
  {
      GiveXPToPC(oPC, fXP);
      AdvanceQuest(OBJECT_SELF, oPC, GetLocalInt(OBJECT_SELF, "quest_kill"));
  }
```

If you want to make it global, you can put it deeper in the system:
script:  inc_xp
lines:  90+

```
    if (GetIsDead(oPC)
        return;    // <--- or send a message/debug/etc.

   int nWisdomMod = GetAbilityScore(oPC, ABILITY_WISDOM) - 10;
   float fXpPercent = 1.0 + (IntToFloat(nWisdomMod) * WISDOM_BONUS);
```

**Comment by b5635** [comment]
I just applied it to the inc, since it's suited for more places if I were to use that XP code anywhere else. Thanks for the tip, btw.
