### ISSUE TITLE
double "summon animal companion"

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#238]
Since it is no longer possible to heal the animal companion via feeding, maybe it's a good idea to allow the double "summon animal companion" then?

**Comment by b5635** [comment]
Sorry about removing it! I think what I will do is re-implement feeding of companions as a down the road sort of thing. We briefly discussed the ideas of it on Discord too. I have a few ideas about items that can be fed and/or corpses :)

I've reopened this issue: https://github.com/b5635/the-frozen-north/issues/195 and close this.
