### ISSUE TITLE
Group Dungeons

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#242]
I remember a conversation in discord about group/highlevel dungeons where you MUST form a party to have success.

**Comment by b5635** [comment]
Working on one right now, but I'll keep this issue open until several are out :)

**Comment by b5635** [comment]
I'd say there are a few group dungeons out right now. We will have a bit more for sure i.e. dungeons that are 15+. Especially if you consider doing higher level dungeons while lower level.
