### ISSUE TITLE
Re-evaluate area init and refreshing scripts, TMIs were encountered and became infinitely looping

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#26]

**Comment by tinygiant98** [comment]
Do you have any details on the conditions that put you into TMI in `area_init`?  `area_refresh` doesn't look like it'd be much of an issue, but I see a few places it could have in `area_init`.

**Comment by b5635** [comment]
The main issue was that I was checking through too many triggers in my spawn system. I just changed it from 5 to 1, and the TMIs seemed to have stopped for now. It's pretty expensive as it loops through every single tile. As a consequence I had to re-design every area to only have one trigger type per elevation. I'll wait for a playtest before I close this issue off, though.
