### ISSUE TITLE
lower the lock DC on the door leading deeper into the prison

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#280]
It happened again today that Lerdon didn't drop his key. I don't know what's causing it, but it could be good if the lock DC on the door was lower so you can bash it. Right now it's a 24.

**Comment by b5635** [comment]
I think the DC should be kept, its just the fact that the key isn't dropping is the real issue. The optional unlocking part is meant for skipping the keyholder boss, if you have enough strength/open lock

**Comment by b5635** [comment]
Might be fixed now
