### ISSUE TITLE
Gilles didn't drop his quill

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#281]

**Comment by mautschi** [comment]
![20210516075412_1](https://user-images.githubusercontent.com/83913954/118387010-2a916800-b60b-11eb-90ad-da477c5601e5.jpg)

**Comment by mautschi** [comment]
I think this happened because I had to flee to the basement before I  could kill him.

**Comment by b5635** [comment]
I believe the two are not related. It's likely that that treasure was not dropped

**Comment by b5635** [comment]
https://github.com/b5635/the-frozen-north/commit/4b0f7aaa215f86517ed9b9e3df15d187ed617759
