### ISSUE TITLE
add Point Blank Shot for Archers/Hunters/Bandits etc.

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#293]
And the crossbow-wielding False Helmites, too

**Comment by mautschi** [comment]
and add maybe rapid reload to enemys lvl 8 and above so they can use their 2 attacks/round

**Comment by b5635** [comment]
Thank you for the note! I'll keep it in mind for high level crossbow enemies, which could be the drow

I probably wont add PBS to the others as it is now fixed!
