### ISSUE TITLE
change the DEX penalty of Aramil's Blade

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#298]
I stumbled upon this sword and saw that it retains it's DEX penalty (-4) from vanilla (where it required lvl 25), but lacks the STR bonus (+8). Maybe it's a good idea to change it to -2 DEX and +2 or even +4 STR?

**Comment by b5635** [comment]
I think that will be a good change, maybe -2 DEX +1 STR or something like that. I will need to first modify the 2das so having a negative ability will make items cost more (and so you can therefore put more attributes)

**Comment by mautschi** [comment]
I think it should be +2 STR, you basically swap 1 AC for 1 AB this way.
