### ISSUE TITLE
change the stream in Thundertree

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#323]
Currently the stream there is floating down on both sides of the water mill. The area should be lower or higher to represent a realistic stream.
![20210521094340_1](https://user-images.githubusercontent.com/83913954/119144202-f7e6d580-ba37-11eb-97c2-a01f407fe53f.jpg)

**Comment by b5635** [comment]
I've tried taking a stab at it, no dice unfortunately. There seems to be a higher part of the watermill which is half of the grass half height tile. I can't seem to connect it to higher water.

![watermill](https://user-images.githubusercontent.com/15935426/119239295-ffbc7d80-bafc-11eb-9f1f-03ba8701891a.png)

Any recommendations? If anyone is interested in revamping this area too, that would be nice as well.
