### ISSUE TITLE
idea: place the third Druid Orlane in a spider cave in the Neverwinter Woods, combined with a spider queen bounty

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#328]

**Comment by tinygiant98** [comment]
Think pok was going to put the last Druid in Castle Jhareg.

**Comment by mautschi** [comment]
Yes, I came up with that setting because one of them was in a spider cave in the OC, too.

**Comment by b5635** [comment]
I forgot that they were in the spider cave. Then let's stick to the OC in this case. As a side note, we'll need to think of a way or another quest to introduce the player to Castle Jhareg as I'm not sure if cultists are part of the storyline in this PW
