### ISSUE TITLE
Doors are misaligned in the Neverwinter City

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#333]
Screenshot credit: Qlippoth

![](https://cdn.discordapp.com/attachments/718492633714131005/845902515936952340/unknown.png)

**Comment by SeanMJOBrien** [comment]
There IS a round topped door, but it appears to be specific to a particular doorway. It might be a bug that this door design is not available in that doorway. I'll try to see if it works, or file a bug if it doesn't. Now I can't find where it is in Docks for the life of me to take a picture so someone believes me.
