### ISSUE TITLE
Gilles didn't drop his quill again

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#334]

**Comment by b5635** [comment]
Hmm, I'm looking at the quest variables but they look alright. I'll give it a whirl myself and report back. If Gilles doesn't drop any loot at all, I might know what the issue is.

**Comment by mautschi** [comment]
IIRC there was no loot bag from him, yes

**Comment by b5635** [comment]
I don't see any reports on this, closing for now.
