### ISSUE TITLE
Trivial: All transition destination waypoints should be pointing appropriately for arrival

### ISSUE THREAD

**Issue by SeanMJOBrien** [b5635/the-frozen-north#338]
The transition between City Core and Beggar's Nest are at their default North heading. They should point into the area so the player is facing the right direction.
![image](https://user-images.githubusercontent.com/11039906/119279614-a8dca400-bbe1-11eb-8509-24810ae1675e.png)

**Comment by SeanMJOBrien** [comment]
**All transitions using triggers I can find:**
Highcliff: HighcliffToMere
MereOfDeadMen - North: MereToHighcliff
Beggar's Nest: BeggarsToCore
CityCore: CoreToBeggars
Neverwinter Wood North: NNorthToNNWest
Neverwinter Wood - Northwest: NNWestToNNorth
Neverwinter Wood - Northwest: NWWestToNWest
Neverwinter Wood - West: NWestToNWWest
Neverwinter Wood - West: NWoodToThundertree
Port Llast Eastern Plains: EastPlainsToNortheastPlains
Port Llast Eastern Plains: EastPlainsToSouthRoad
Port Llast Northeast Plains: NorthEastPlainsToEastPlains
Port Llast South Road: SouthRoadToEastPlains
Thundertree: ThundertreeToNWood

**Comment by b5635** [comment]
t_c_r: When leaving the lizard village and entering the (second zone of the) swamp there is another incorrect facing.

**Comment by b5635** [comment]
I just checked it in the toolset, the cave entrance appears to have the correct facing.
