### ISSUE TITLE
Once: Summoned Tyrantfog Zombie was stunned through some mind control

### ISSUE THREAD

**Issue by SeanMJOBrien** [b5635/the-frozen-north#361]
I'm not sure what the effect was, I got a screenshot just after it faded. It was the blue and purple rungs around the head.
This was in the Goblin Caves.

**Comment by b5635** [comment]
Strange. Maybe an evil cleric used turn undead and dominnated him?

**Comment by b5635** [comment]
I'll close this for now as it doesn't seem to have happened to anyone else. Feel free to re-open if you encounter it again.
