### ISSUE TITLE
Fenthick is psyching me out instead of healing me.

### ISSUE THREAD

**Issue by SeanMJOBrien** [b5635/the-frozen-north#363]
It sometimes takes more than one try to get Fenthick to fully perform his healing magic. He'll start, but half way through he'll stop casting and leave me hangin'.

**Comment by b5635** [comment]
Oh, I had thought I fixed this bug. I'm not sure what's going on, could be that a random idle animation is causing it to cancel. I could probably make him "fake cast" and then cast it instantly so it is guaranteed to work

**Comment by b5635** [comment]
I'll make it so Fenthick and the other healers won't wander. That is probably what cancels out the casting.
