### ISSUE TITLE
Seating

### ISSUE THREAD

**Issue by SeanMJOBrien** [b5635/the-frozen-north#372]
Adding seating to all drinking and meeting places.
Silver Serpent Inn, Moonstone Mask, Seedy Tavern?, etc.

NPCs should probably also know how to sit down, too.

**Comment by b5635** [comment]
I think this would be great, yes! A few players have requested it as well when I added this issue #181

**Comment by SeanMJOBrien** [comment]
This is started and working well. It just needs to be expanded throughout the modules' more public areas.

**Comment by SeanMJOBrien** [comment]
Golden Apple
Seedy Tavern
Shining Serpent Inn
Moonstone Mask
Trade of Blades
Alliance Arms Inn

**Comment by b5635** [comment]
I think these areas have it now. Nice work on adding these!
