### ISSUE TITLE
Barkskin balance tweak

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#443]
Consider adding it to the same scaling as GMW and the magic armor spells, it's pretty strong at low levels

**Comment by b5635** [comment]
I think it is fine to keep, makes druids good / worthwhile.

Also makes plant domain good for clerics

**Comment by lootabox** [comment]
This is easily the strongest AC buff in the game right now. At level 7 its +4 AC while also freeing up the amulet slot.

I think druids and clerics are in top 3 strongest classes anyway, I don't think they need this power. This buff would be really good even with the reduced scaling.
