### ISSUE TITLE
Restoration access is severely limited to the point of being extremely annoying

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#499]
Having to spend 5 minutes to go to Thundertree and back when a Helm's Hold wight level drains you is not terribly exciting gameplay.

**Comment by b5635** [comment]
I think it will be good to add some sort of restorative "fountain" inside Helms Hold that just cures the PC and friends.

**Comment by Logg-y** [comment]
I missed that Fenthick sells an unlimited number of them at 880g each. This is still quite expensive, though...
