### ISSUE TITLE
Henchmen killed by death rays don't reset properly

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#502]
Their corpses do not stay on the ground to be resurrected by proximity.
When talking to them after respawning, they respond as if they never left your party.

**Comment by b5635** [comment]
Is this the instant kill ray from beholders or is it from petrification?

Also, which henchman was it? If it's from Nathyrra or Valen in particular I may have missed setting a few variables

**Comment by Logg-y** [comment]
Unfortunately I forget which one(s) this was, but it was definitely one or the other (or both) of the Underdark henchmen.
