### ISSUE TITLE
Horses in combat are probably too effective

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#525]
"Right now you can ignore 99% of enemies by just running through with a horse. I think the old chance to fall off wasn't great, but also I feel like there's a little bit too much freedom with them now" - LootaBox

Probably means that a bigger AC/AB penalty is needed.

The spell failure effect while mounted does not function.

**Comment by b5635** [comment]
https://github.com/b5635/the-frozen-north/commit/216d8c9a99ad462fa90219af1ccbdae8f879c95d
