### ISSUE TITLE
Horse changes

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#533]
* Change base AC penalty from -4 to -2
* Remove base AB penalty (unchanged for range)
* Require mounted combat feat for AC bonus

**Comment by Logg-y** [comment]
Side note: Paladin mount ability (spell 818, x3_s3_palmount) cannot be used to dismount in combat as it gets caught by the cannot cast spells in combat while mounted stuff.

**Comment by b5635** [comment]
I think you can cast spells on horses now.
