### ISSUE TITLE
Heart of the Wood -> Spirit of the Wood is too difficult

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#562]
Realistically you get there at level 6 without replaying things a lot.

Shadow druid elites themselves are level 6
Regulars are level 4

Spirit realm entry fight has 2x Elite and 3x Regular, PLUS one random spawn point
Especially with henchman AI's tendency to target the two summons per druid this is extremely problematic at level 6, even when you know it is coming and have two henchmen

The rest of the heart of the forest area is completely trivial compared to this, making the final fight less terrifying and ramp up more gradually

Inside is also not great, due to the spirit itself being an invulnerable henchman magnet, and the large numbers of (elite) druids. Might be okay if the spirit didn't attack you too...

My experience thus far is that you either have to get lucky or wipe and throw yourself at it several times

Adjust ACR of spirit realm from 7 to 6 afterwards too

Fast travel from Aawill to the Heart of the Wood ("You follow the path Aawill told you about") and maybe back again (though you can enter the realm of the spirit and go straight to the druid camp) would skip a LOT of backtracking, which might be nice

**Comment by lootabox** [comment]
I fully agree that the entrance fight is a bit overtuned.

Aawil could clearly mention that the spirit couldnt be harmed to avoid confusion, if the henchman AI could be adjusted so they didnt attack the spirit either that would make things easier.

Other than that the fight is pretty much okay... the main gripe I have with the spirit fight or the woods in general is that there is no temple at the druid camp. If you die, for whatever reason, you have quite a journey to get back there - likely without a horse either.

I dont remember the dialog now, but why couldnt the spirit just read your mind and teleport you straight to the dryad..? Aawil could be like "you wont find the dryad unless she wants to be found, but the spirit could guide you to her nontheless" - no need to jump to Aawil in between

**Comment by lootabox** [comment]
Alternatively in the spirit fight - perhaps you could beat the spirit to 1hp so they go down for a while, but then get back up again. I think this mechanism exists in the game - at least I saw something like that with Bjorlam getting beaten by the angry dwarven commoner.
