### ISSUE TITLE
Allow healers to buff players

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#564]
I.e. Bless at level 1, maybe a stat buff at level 5, or 6

**Comment by lootabox** [comment]
I would also grant access to endure elements and protection from alignment. These are very useful spells that a cleric gets access to at level 1.

**Comment by b5635** [comment]
Sure, I don't see why not.

Reminder for me to script it in a way so that the spell is applied to all followers, but also only one can be in affect at a time.
