### ISSUE TITLE
Paladin henchman Mischa is not really responsive in combat

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#569]

**Comment by b5635** [comment]
Doesn't appear to be missing any scripts

**Comment by b5635** [comment]
Still an issue. She seems to be doing nothing, maybe stuck trying to do a spell or something?

**Comment by Logg-y** [comment]
Thinking about this, they (and the paladin adventurers) might be trying to use the class summon mount ability.

Changing the AI category in spells.2da on the serverside alone might maybe help...?

**Comment by b5635** [comment]
This should be fixed now, didnt experience her standing still
