### ISSUE TITLE
Boat/Ferries should probably use NWNX_Creature_ComputeSafeLocation

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#606]
This seems to fail when something (usually another player) is already on top of the jump spot in the boat
Using NWNX_Creature_ComputeSafeLocation to find a free space to jump them likely has a better chance of success

**Comment by b5635** [comment]
Sounds good. I wonder if there's something more reliable than ActionJumpToLocation, or a force jump.

If not, it would be good to edit the script to NOT take gold.
