### ISSUE TITLE
Traps difficulty progression may not be right

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#642]
While rare, it is possible to roll things like the minor electrical trap in CR 2 areas. 8d6 DC 19 for half that strikes an area can happily kill an entire party instantly which doesn't feel great.

Traps feel like they go from extremely harsh (start of the game) to pretty negligible later. It might be worth revisiting this a bit.

**Comment by b5635** [comment]
hopefully this is fixed, can re-open if we see it crop up again
