### ISSUE TITLE
Decrease amount of moving commoners

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#69]
They tend to get stuck on each other due to poor pathfinding.

**Comment by tinygiant98** [comment]
The stacking issue would probably be less if you increased the number of commoner waypoints and increased the spawn delay spread.

**Comment by b5635** [comment]
Thanks, I'll try that. I also notice that the first time a player enters the area, a whole bunch of them groups too, possibly due to the AI level which I think increasing the delay may help.

Unfortunately not all areas in the server support multiple waypoints, as for example the academy may only have two doors.

**Comment by tinygiant98** [comment]
True, in those cases (or in all of them), maybe try setting the min delay a bit higher (4-5 seconds, maybe more?) so it gives time for the PC and their party to get in and start moving before the commoners stack up on them.

**Comment by tinygiant98** [comment]
If you wanted to go too far with it, you could even check for PCs within a radius of the waypoint before spawning.

**Comment by b5635** [comment]
I think the biggest problem that I inadvertently did was disabling the original check for when PCs are in the area, and just letting the system run anyways, as I wanted it look like it happened in the background regardless of players.

**Comment by tinygiant98** [comment]
One way to do that would be to have multiple crowds.  One very small (maybe 2-3 commoners) that is always there.  Then, when the PCs arrive, spawn the additional crowds.
