### ISSUE TITLE
Auras still persist after death

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#710]
For whatever reason, [this](https://github.com/b5635/the-frozen-north/blob/88110c263475372a70755d39da98566e6312d6ab/src/nss/ai_ondeath.nss#L73-L78) didn't fix it

**Comment by b5635** [comment]
it might be the edge-case where an enemy may have multiple AoEs set, as this just sets the last AoE. What enemy was this encountered on and what aura?

For context, it seems like the community patch does some sort of weird workaround/trick to spawn an AoE as an... object? placeable? Maybe we just need to do away with that and move it back to vanilla functionality.

Anyways, before the commit I tested it on a Ghast which has a tyrantfog aura, which cleaned it up after death.

**Comment by b5635** [comment]
Fixed, thanks Loggy!
