### ISSUE TITLE
Address logging in at valuable places, looting it/killing bosses and logging out until refresh

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#711]
From Discord discussions pok's preferred way to go about this is to boot a player somewhere dangerous within the same area if they login within a certain distance of a boss. I'm not sold on this because...

1) It makes blocking all the possible places where you can log in and get way too much loot for doing literally nothing much more difficult. There are many dungeons split over multiple areas, some (and probably more in the future) with proportionally large rewards weighted heavily at the end. Simply booting you somewhere else in the area you logged into means you can still skip the vast majority of the dungeon. That is, unless someone takes the time to go through and special case every single one of these instances.
1b) Some of the point of the loot changes was to incentivise full completions of areas, and simply throwing a player capable of soloing the entire area at the start of the last subarea flies in the face of that because they still get to skip most of the stuff that is intended to be gone through to get there. 
2) Piles of big chests in semi-safe or easily soloable rooms are as much valid targets for this as things flagged as bosses, and there will be some places where they aren't near or in areas with bosses. Again, preventing abuse of this means going through and special casing every one of those.
3) When combined with back-loaded loot as we now have, not kicking out people fully is incentivsing any character who can safely log into a dungeon mid completion, grab the loot, log out and repeat to do exactly that, rather that playing the dungeons the intended way because it's simply more time efficient. I very much disagree with creating a situation where this is the case.
4) Booting people out all the way is not abusable even from a travel point of view, because you'd have to wait up to 1h for the area to refresh before you get moved. And if you cleared your way there already, backtracking manually would take a few minutes at most.

All in all I'm in favour of booting people out all the way because...

1) It's arguably less work, both to implement now and in the long run. Implementing the move-to-same-area-as-boss-if-near way might sound simpler, but after addressing all the spots where that doesn't work (eg isle of the maker, any other place that has semi-safe rooms with multiple large chests in) it doesn't sound any less work. And then it would need doing again for every new area...
2) Simply setting a waypoint tag on an area for "if a player logged into this area after a refresh, take them here" sounds a little neater. And some of the stuff to try to address the above probably devolves into this anyway.

**Comment by b5635** [comment]
My main idea/concern for the former is that a player should make sure to log out in a safe place. If they are in a non-soloable area and they log-in without players/help/henchman death is likely and that should be the case - logging in at the start of a dungeon and being able to escape would be a situation that isn't ideal IMO.

That said I think the second makes sense too. This is the MMO model that I see a lot as well - if you come back in a dungeon whether you are near a boss or in the middle, you start at the beginning of a dungeon.

---

Maybe we need to be a bit more specific about the exact logic.

IF your level is at the within 1 CR or higher of the dungeon, you are teleported to the beginning of the dungeon. This implies that you may be capable of farming this dungeon. For the Maker, this means that if you are level 11 or level 12 you are teleported to the start.

IF below or a bit below the CR, assume that you aren't capable of solo-ing and you must fight your way out. Maybe 2 levels below?

---

But we can do this later / think about it later. I think its fine to teleport players to the start of a dungeon (they still need to fight their way back from the wilderness / underdark / etc). FYI I do try to set waypoints near the entrance of a dungeon (map note "Exit"), we can probably leverage those.

**Comment by Logg-y** [comment]
There is also no reason why jumping people back to the start of the dungeon HAS to be completely safe - but it might let you get out where fighting your way out alone through the entire refreshed area would wipe you.

Level gating would help many cases but also means that multiple people coordinating can log in together at a boss and be okay to repeatedly farm it still... so long as they keep coordinating.

Another option would be to massively reduce loot drop rates of all linked areas if you logged in after a refresh, but that also has its problems. I don't think there is going to be a "perfect" solution here, but I'm really leaning towards warping to somewhere just inside or outside as being the solution with the least amount of abuse potential. I guess I'd rather people get out of situations that should probably kill them than incentivise not playing through the whole dungeons.

**Comment by b5635** [comment]
I actually didn't think of people coordinating a login. Very valid point!

In that case, I think the most feasible solution is the one you posed where we just teleport people to the begining of a dungeon.

**Comment by b5635** [comment]
This is done now, thanks Loggy!
