### ISSUE TITLE
Respawning should Greater Restoration surviving henchmen, possibly also consider instant respawning henchmen under your command

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#751]
1) Damaged henchmen end up drinking potions in the temple. Confused henchmen can end up attacking the immortal NPCs which means they just die, get respawned and then attacked again. (Unconfirmed, but it might also be possible for them to murder "innocents" which might reflect on the leader's alignment too.) Both of these behaviours are not great. You're incentivised not to wait for them to die fully to avoid the 5min respawn wait, which leads to...

2) Dead henchmen persisting for 5 minutes even after full wipe and respawn to temple sucks. If you want more, you have to get them with persuade. And you can't get the "good" henchman because they're still dead on the floor without sitting and waiting and doing absolutely nothing interesting for 5 minutes.

Playing with henchmen is already a frustration point because of their poor AI (and, to a much lesser extent their worse builds/equipment than what players assemble) this just makes it feel even worse.

Henchmen staying dead on the floor for 5 minutes even if the master is out of area is great when you need to run away, but when you wipe fully back to a temple it's just not fun.

**Comment by b5635** [comment]
We should consider if we should abandon _all_ henchman and followers upon respawning or teleporting back. It's sort of odd that they come back with you at all.

I'll implement it as is, but something to think about.
