### ISSUE TITLE
Stat tracking

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#752]
~Enemies killed~
~Bosses killed~
~Quests completed~
~Assassination attempts thwarted~
~Bounties completed~
~Treasure maps completed~
~Strongest enemy killed: Name of the strongest enemy you have killed. This is stored by comparing the CR, add +1 if it was from a boss~
~Deaths: Not sure if we want to ignore unknown object deaths such as from logging in~
~Respawns~
~Followers hired~
~Gold looted: From personal loot only?~
~Gold earned from selling~
~Chests looted~
~Most gold carried~
~Innocents killed: Commoner faction~
~Times rested~
~Persuasions~
~Bluffs~
~Henchman hired~
~Followers died~
~Henchman died~
Critters killed: Hard to categorize atm
~Spells cast~
~Spells cast from item~
~Potions drunk~
~Own Spells interrupted~
~Enemy spells interrupted~
~Pickpockets succeeded/failed~
~Locks unlocked~
~Locks bashed~
~Times rested in house~
~Hours waited in house~

**Comment by Logg-y** [comment]
Another fun thing would be to write these to the cdkey DB as well, so you can view totals across all characters (vs having to add it up manually)

**Comment by b5635** [comment]
Feel free to add more to the list as well. We can keep this issue alive for a while

**Comment by Logg-y** [comment]
Value of items assigned to henchmen, so you can feel sad at RNG (or you can see the balance code actually works and probability doesn't truly hate you)
Time played might be interesting or just depressing (did you cull it for some reason from the discord list?)
Times revived seems a little pointless (respawns - times died should give you this)
Percent of kills in party (requires storing direct kill count vs total party kill count)
Percent of xp value from kills in party (same with xp)
Ferries used
Long transport (currently just boats, but might be more things later?) taken
Party members killed (via friendly fire or charm)
Traps triggered
Traps disarmed/recovered
Deaths to traps

**Comment by b5635** [comment]
I added it Time played but may have removed the wrong entry when cleaning up the list

We can hook saving throws for sure, I think we have something for that or at least for spells

I like all of those, especially percent of kills in party. Reminds me of the infinity engine days!

I'll add in some of the easy low hanging fruit. Some of them need to be added now for it to make sense (i.e. value of items assigned to henchman)

**Comment by b5635** [comment]
for percentage of party kills, I'm opting to do `enemies_killed_with_credit` and hook it to `party_credit`. This works for party cases and the case where a neutral, non-party NPC assists. Or even due to enemy in-fighting

**Comment by Logg-y** [comment]
#756 has added this, I just forgot to link in the PR.
