### ISSUE TITLE
Humanoid creatures are dropping bioware remains on refresh

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#775]
I don't know why this is. My first thought is pickpocket items. It seems to be one item every time, and I think all I've checked have been nonequippable.

This is probably caused by droppable flagged items being put in inventories somewhere.

**Comment by b5635** [comment]
What items are they dropping?

**Comment by Logg-y** [comment]
Scrolls, gems, copper rings, and the misc/clutter items.
