### ISSUE TITLE
Henchmen not responding to being attacked

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#777]
This is especially problematic when the player is dead and can't command them to fix it. Then the only option is to log out and back in which seems to make them do something, but by that time they've been used as a punching bag for several rounds and you wipe because of it, which is pretty frustrating.

Messing with [Jasperre's debug stuff](https://github.com/b5635/the-frozen-north/blob/master/src/nss/j_inc_debug.nss) and maybe enabling some of it might help with figuring out the issue.

**Comment by b5635** [comment]
two fixes resolved this,

one was returning TRUE for doing a combat round when the master was dead, other was to always return false instead of a combat check for GetIsFighting, both of which are in j_inc_constants
